export const currencyByTaka: Currency[] = [
  { name: 'USD', value: 0.009113, flag: '🇺🇸', symbol: '$' }, // United States Dollar (USD)
  { name: 'EUR', value: 0.008278, flag: '🇪🇺', symbol: '€' }, // Euro (EUR)
  { name: 'JPY', value: 1.2300, flag: '🇯🇵', symbol: '¥' }, // Japanese Yen (JPY)
  { name: 'GBP', value: 0.007042, flag: '🇬🇧', symbol: '£' }, // British Pound (GBP)
  { name: 'AUD', value: 0.014023, flag: '🇦🇺', symbol: 'A$' }, // Australian Dollar (AUD)
  { name: 'CAD', value: 0.012345, flag: '🇨🇦', symbol: 'C$' }, // Canadian Dollar (CAD)
  { name: 'SGD', value: 0.006889, flag: '🇸🇬', symbol: 'S$' }, // Singapore Dollar (SGD)
  { name: 'CHF', value: 0.008834, flag: '🇨🇭', symbol: 'CHF' }, // Swiss Franc (CHF)
  { name: 'CNY', value: 0.059231, flag: '🇨🇳', symbol: '¥' }, // Chinese Yuan (CNY)
  { name: 'INR', value: 0.70456, flag: '🇮🇳', symbol: '₹' }, // Indian Rupee (INR)
  { name: 'MYR', value: 0.022048, flag: '🇲🇾', symbol: 'RM' }, // Malaysian Ringgit (MYR)
  { name: 'THB', value: 0.27234, flag: '🇹🇭', symbol: '฿' }, // Thai Baht (THB)
  { name: 'IDR', value: 131.34, flag: '🇮🇩', symbol: 'Rp' }, // Indonesian Rupiah (IDR)
  { name: 'KRW', value: 11.423, flag: '🇰🇷', symbol: '₩' }, // South Korean Won (KRW)
  { name: 'BRL', value: 0.005428, flag: '🇧🇷', symbol: 'R$' }, // Brazilian Real (BRL)
  { name: 'MXN', value: 0.17348, flag: '🇲🇽', symbol: '$' }, // Mexican Peso (MXN)
  { name: 'ZAR', value: 0.70452, flag: '🇿🇦', symbol: 'R' }, // South African Rand (ZAR)
  { name: 'RUB', value: 0.13428, flag: '🇷🇺', symbol: '₽' }, // Russian Ruble (RUB)
  { name: 'TRY', value: 0.14285, flag: '🇹🇷', symbol: '₺' }, // Turkish Lira (TRY)
  { name: 'AED', value: 0.034231, flag: '🇦🇪', symbol: 'د.إ' }, // United Arab Emirates Dirham (AED)
  { name: 'HKD', value: 0.074023, flag: '🇭🇰', symbol: 'HK$' }, // Hong Kong Dollar (HKD)
  { name: 'NOK', value: 0.13785, flag: '🇳🇴', symbol: 'kr' }, // Norwegian Krone (NOK)
  { name: 'PLN', value: 0.02734, flag: '🇵🇱', symbol: 'zł' }, // Polish Zloty (PLN)
  { name: 'NZD', value: 0.015023, flag: '🇳🇿', symbol: 'NZ$' }, // New Zealand Dollar (NZD)
];

  